/*
 * @Author: jinx
 * @Date: 2021-11-09 16:07:09
 * @LastEditors: jinx
 * @Descripttion: 模拟表格数据
 */
export const mockData = {
    "records": [{
      "deviceId": 8002,
      "terminal": "00000810101265",
      "deviceType": "LDX-8-WHITE",
      "shop": {
        "name": "来电909",
        "address": "广东省深圳市南山区深圳湾公园"
      },
      "healthScore": 0,
      "coord": {
        "lat": 41.789052,
        "lng": 123.393365
      },
      "deviceState": 3,
      "offlineTime": "266天21小时",
      "totalChannel": 8,
      "currCDBCnt": 2,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["满仓", "离线超时天数:266"],
      "updateTime": "2020-08-12 14:14:02",
      "takeOfferCnt": 0,
      "reasonableValue": 0,
      "children": [{
        "deviceId": 1,
        "terminal": "00000810101260",
        "deviceType": "LDX-8-WHITE",
        "shop": {
          "name": "来电909",
          "address": "广东省深圳市南山区深圳湾公园"
        },
        "healthScore": 0,
        "coord": {
          "lat": 41.789052,
          "lng": 123.393365
        },
        "deviceState": 3,
        "offlineTime": "266天21小时",
        "totalChannel": 8,
        "currCDBCnt": 2,
        "rentNotReturnCnt": 0,
        "avgRentTimes": 0,
        "exceptionItem": ["满仓", "离线超时天数:266"],
        "updateTime": "2020-08-12 14:14:02",
        "takeOfferCnt": 0,
        "reasonableValue": 0,
        }]
    }, {
      "deviceId": 1580,
      "terminal": "000012000243",
      "deviceType": "UNDEFINED-DEVICE",
      "healthScore": 0,
      "deviceState": 3,
      "offlineTime": "525天22小时",
      "totalChannel": 1,
      "currCDBCnt": 8,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["回收仓归还:1", "满仓", "离线超时天数:525", "禁止借充电宝"],
      "updateTime": "2019-11-27 13:03:00",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 195983,
      "terminal": "000050000495",
      "deviceType": "NAS-50",
      "shop": {
        "name": "海娃大厦",
        "address": "广东省深圳市南山区粤海街道深南大道9942海王银河科技大厦19\n1"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.541077,
        "lng": 113.941685
      },
      "deviceState": 3,
      "offlineTime": "427天17小时",
      "totalChannel": 25,
      "currCDBCnt": 1,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:427", "仓道异常:1", "被禁用充电宝:7"],
      "devopsTask": [{
        "taskId": 477,
        "status": 4,
        "taskType": 4
      }, {
        "taskId": 481,
        "status": 1,
        "taskType": 4,
        "dealUserName": "李宇江-产品研发部-运维主管"
      }],
      "updateTime": "2020-05-21 17:51:47",
      "takeOfferCnt": 19,
      "reasonableValue": 0
    }, {
      "deviceId": 3740,
      "terminal": "000020000396",
      "deviceType": "LDX-20",
      "healthScore": 0,
      "deviceState": 3,
      "offlineTime": "525天22小时",
      "totalChannel": 20,
      "currCDBCnt": 16,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:525"],
      "updateTime": "2019-11-27 13:52:42",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 21652,
      "terminal": "00000810113070",
      "deviceType": "LDX-8-WHITE",
      "shop": {
        "name": "测试网点5544",
        "address": "广东省深圳市南山区科技生态园2区，地上广东省深圳市南山区科技生态园2区，地上"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.530557,
        "lng": 113.952712
      },
      "deviceState": 3,
      "offlineTime": "266天21小时",
      "totalChannel": 8,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:266"],
      "updateTime": "2020-08-12 14:18:02",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 306246,
      "terminal": "000025000453",
      "deviceType": "NAS-SAY-25",
      "shop": {
        "name": "测试海王1",
        "address": "海王银河科技大厦19091"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.540685,
        "lng": 113.941539
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 25,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:344"],
      "devopsTask": [{
        "taskId": 383,
        "status": 1,
        "taskType": 2,
        "dealUserName": "覃桂宜-产品研发部-Web前端开发工程师"
      }, {
        "taskId": 413,
        "status": 4,
        "taskType": 4
      }, {
        "taskId": 421,
        "status": 4,
        "taskType": 4
      }, {
        "taskId": 455,
        "status": 1,
        "taskType": 5,
        "dealUserName": "代文-测试来电科技-一级合伙人"
      }, {
        "taskId": 595,
        "status": 1,
        "taskType": 2
      }, {
        "taskId": 596,
        "status": 1,
        "taskType": 1,
        "dealUserName": "熊唐雨-测试运维部-运维主管"
      }, {
        "taskId": 597,
        "status": 1,
        "taskType": 2,
        "dealUserName": "吴振兴-测试运维部-运维"
      }, {
        "taskId": 599,
        "status": 1,
        "taskType": 1,
        "dealUserName": "熊唐雨-测试运维部-直营-运维"
      }],
      "updateTime": "2020-08-12 14:17:39",
      "takeOfferCnt": 14,
      "reasonableValue": 0
    }, {
      "deviceId": 208735,
      "terminal": "0000001829114283",
      "deviceType": "NAS-04",
      "shop": {
        "name": "海王测试大厦",
        "address": "广东省深圳市福田区华强北街道振兴路341女人世界外贸城(振兴路)123123"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.547088,
        "lng": 114.086114
      },
      "deviceState": 3,
      "offlineTime": "603天21小时",
      "totalChannel": 0,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:603"],
      "updateTime": "2019-11-27 13:31:42",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 5873,
      "terminal": "000008000589",
      "deviceType": "LDZ-8",
      "shop": {
        "name": "开发经理要求测试",
        "address": "广东省深圳市福田区华强北街道顺电(华强北路)上步工业区sfdsdafdsa"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.547482,
        "lng": 114.086362
      },
      "deviceState": 3,
      "offlineTime": "266天21小时",
      "totalChannel": 8,
      "currCDBCnt": 3,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:266"],
      "updateTime": "2020-08-12 14:18:23",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 121971,
      "terminal": "0000000399585978",
      "deviceType": "NAS-08",
      "shop": {
        "name": "海王来电网点111",
        "address": "广东省深圳市南山区海王银河科技大厦\n123123"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.540766,
        "lng": 113.941498
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 8,
      "currCDBCnt": 5,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["满仓", "离线超时天数:344", "被禁用充电宝:2", "疑似异常:1"],
      "devopsTask": [{
        "taskId": 388,
        "status": 1,
        "taskType": 2,
        "dealUserName": "深圳BOM - 张俊峰"
      }, {
        "taskId": 1176,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1177,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1178,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1179,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1181,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1182,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1183,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1184,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1188,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1189,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1190,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1191,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1192,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1193,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1194,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1195,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1203,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1204,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1205,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1206,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1207,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1208,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1209,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1210,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1211,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1212,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1213,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1214,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1215,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1216,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1217,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1218,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1234,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1235,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1236,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1237,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1238,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1239,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1240,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1241,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1242,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1243,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1244,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1245,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1246,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1247,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1248,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1249,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1250,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1251,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1252,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1253,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1254,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1255,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1256,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1257,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1258,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1259,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1260,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1261,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1262,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1263,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1264,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1265,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1297,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1298,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1299,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1300,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1301,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1302,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1303,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1304,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1305,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1306,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1307,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1308,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1309,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1310,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1311,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1312,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1313,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1314,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1315,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1316,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1317,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1318,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1319,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1320,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1321,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1322,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1323,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1324,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1325,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1326,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1327,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1328,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1329,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1330,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1331,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1332,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1333,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1334,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1335,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1336,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1337,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1338,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1339,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1340,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1341,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1342,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1343,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1344,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1345,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1346,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1347,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1348,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1349,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1350,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1351,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1352,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1353,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1354,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1355,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1356,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1357,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1358,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1359,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1360,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1424,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1425,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1426,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1427,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1428,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1429,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1430,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1431,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1432,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1433,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1434,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1435,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1436,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1437,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1438,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1439,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1440,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1441,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1442,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1443,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1444,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1445,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1446,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1447,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1448,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1449,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1450,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1451,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1452,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1453,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1454,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1455,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1456,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1457,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1458,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1459,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1460,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1461,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1462,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1463,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1464,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1465,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1466,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1467,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1468,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1469,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1470,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1471,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1472,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1473,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1474,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1475,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1476,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1477,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1478,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1479,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1480,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1481,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1482,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1483,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1484,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1485,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1486,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1487,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1488,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1489,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1490,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1491,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1492,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1493,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1494,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1495,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1496,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1497,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1498,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1499,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1500,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1501,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1502,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1503,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1504,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1505,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1506,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1507,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1508,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1509,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1510,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1511,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1512,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1513,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1514,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1515,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1516,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1517,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1518,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1519,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1520,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1521,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1522,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1523,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1524,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1525,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1526,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1527,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1528,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1529,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1530,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1531,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1532,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1533,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1534,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1535,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1536,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1537,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1538,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1539,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1540,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1541,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1542,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1543,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1544,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1545,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1546,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1547,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1548,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1549,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1550,
        "status": 1,
        "taskType": 1,
        "dealUserName": "刘耀庭-产品研发部-维修组长"
      }, {
        "taskId": 1551,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇"
      }, {
        "taskId": 1601,
        "status": 1,
        "taskType": 1,
        "dealUserName": "连彦淇-客服部-客服主管"
      }],
      "updateTime": "2020-08-12 14:18:24",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 226739,
      "terminal": "0000000509471740",
      "deviceType": "NAS-08",
      "shop": {
        "name": "商家分成100%2",
        "address": "广东省深圳市福田区华强北街道振兴路341号女人世界外贸城(振兴路)厕所"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.546862,
        "lng": 114.085981
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 0,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:344"],
      "updateTime": "2020-08-12 14:18:24",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 225171,
      "terminal": "0000001368060511",
      "deviceType": "NAS-08",
      "shop": {
        "name": "合夥人測試0071",
        "address": "广东省深圳市福田区华强北街道振兴路341号女人世界外贸城(振兴路)1111"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.54737,
        "lng": 114.086022
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 0,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:344"],
      "updateTime": "2020-08-12 14:18:25",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 124355,
      "terminal": "0000000159604091",
      "deviceType": "NAS-04",
      "shop": {
        "name": "海娃大厦",
        "address": "广东省深圳市南山区粤海街道深南大道9942海王银河科技大厦19\n1"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.540906,
        "lng": 113.941718
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 4,
      "currCDBCnt": 2,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:344", "被禁用充电宝:1", "疑似异常:1"],
      "devopsTask": [{
        "taskId": 173,
        "status": 1,
        "taskType": 1,
        "dealUserName": "郑雪娇-测试分公司-直营-运维"
      }, {
        "taskId": 175,
        "status": 1,
        "taskType": 1,
        "dealUserName": "郑雪娇-测试分公司-直营-运维"
      }, {
        "taskId": 496,
        "status": 4,
        "taskType": 3
      }, {
        "taskId": 497,
        "status": 1,
        "taskType": 3,
        "dealUserName": "郑雪娇-测试分公司-直营-城市仓库管理员"
      }, {
        "taskId": 498,
        "status": 1,
        "taskType": 3,
        "dealUserName": "李宇江-产品研发部-运维"
      }, {
        "taskId": 499,
        "status": 4,
        "taskType": 3
      }, {
        "taskId": 502,
        "status": 1,
        "taskType": 3,
        "dealUserName": "深圳BO - 曾庆欢"
      }, {
        "taskId": 508,
        "status": 1,
        "taskType": 3,
        "dealUserName": "瞿关贸-二级测试来电科技-合伙人运营"
      }],
      "updateTime": "2020-08-12 14:18:33",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 130100,
      "terminal": "0000002120087603",
      "deviceType": "NAS-08",
      "shop": {
        "name": "小宇专业祛痘清颜堂专业祛痘(公园前直营店)\t\t\t\t\t\t",
        "address": "广东省深圳市 南山区海王银河科技大厦19层广东省广州市越秀区  教育路118号2楼(公园前地铁D出口对面)\t\t\t\t\t\t\t1"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.531059,
        "lng": 113.95409
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 1,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:344"],
      "devopsTask": [{
        "taskId": 51,
        "status": 4,
        "taskType": 5,
        "dealUserName": "代文-测试来电科技-一级合伙人"
      }, {
        "taskId": 139,
        "status": 1,
        "taskType": 2,
        "dealUserName": "覃桂宜-产品研发部-Web前端开发工程师"
      }, {
        "taskId": 168,
        "status": 1,
        "taskType": 1,
        "dealUserName": "周云萍-测试分公司-运维"
      }, {
        "taskId": 171,
        "status": 1,
        "taskType": 1,
        "dealUserName": "郑雪娇-测试运维部-直营-运维"
      }, {
        "taskId": 184,
        "status": 1,
        "taskType": 2,
        "dealUserName": "周云萍-测试分公司-运维主管"
      }, {
        "taskId": 553,
        "status": 1,
        "taskType": 1
      }, {
        "taskId": 562,
        "status": 1,
        "taskType": 2,
        "dealUserName": "test00-产品研发部-产品经理"
      }, {
        "taskId": 604,
        "status": 1,
        "taskType": 4,
        "dealUserName": "代文-测试来电科技-一级合伙人"
      }, {
        "taskId": 658,
        "status": 1,
        "taskType": 4,
        "dealUserName": "袁振"
      }, {
        "taskId": 659,
        "status": 1,
        "taskType": 4,
        "dealUserName": "深圳BD - 吴晓青-业务一组-业务员"
      }],
      "updateTime": "2020-08-12 14:18:33",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 227068,
      "terminal": "0000001258616664",
      "deviceType": "NAS-08",
      "shop": {
        "name": "dhj合伙",
        "address": "广东省深圳市福田区华强北街道振兴路341号女人世界外贸城(振兴路)女人世界"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.546885,
        "lng": 114.085937
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 0,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:344"],
      "updateTime": "2020-08-12 14:18:33",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 223533,
      "terminal": "0000001451204470",
      "deviceType": "NAS-08",
      "shop": {
        "name": "hehuoren001",
        "address": "广东省深圳市福田区华强北街道振兴路343号女人世界外贸城(振兴路)sdfsdfsdfsd"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.546954,
        "lng": 114.085993
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 0,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:344"],
      "updateTime": "2020-08-12 14:18:36",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 225220,
      "terminal": "0000001669794496",
      "deviceType": "NAS-08",
      "shop": {
        "name": "DW测试BBBB",
        "address": "广东省深圳市福田区华强北街道振兴路341号上步工业区FFF"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.546962,
        "lng": 114.085965
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 0,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:344"],
      "updateTime": "2020-08-12 14:18:36",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 222802,
      "terminal": "0000001607661884",
      "deviceType": "NAS-08",
      "shop": {
        "name": "dhj合伙人测试3",
        "address": "广东省深圳市福田区华强北街道振兴路343号女人世界外贸城(振兴路)南山区女人世界"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.546949,
        "lng": 114.08578
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 0,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:344"],
      "updateTime": "2020-08-12 14:18:37",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 42319,
      "terminal": "000040199997",
      "deviceType": "DHJ-40",
      "shop": {
        "name": "dhj合伙人测试3",
        "address": "广东省深圳市福田区华强北街道振兴路343号女人世界外贸城(振兴路)1111"
      },
      "healthScore": 1,
      "coord": {
        "lat": 22.54701,
        "lng": 114.086021
      },
      "deviceState": 3,
      "offlineTime": "0小时",
      "totalChannel": 40,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["仓道异常:40"],
      "devopsTask": [{
        "taskId": 256,
        "status": 1,
        "taskType": 1,
        "dealUserName": "熊文鹏-产品研发部-Java开发工程师"
      }, {
        "taskId": 261,
        "status": 1,
        "taskType": 1,
        "dealUserName": "熊文鹏-产品研发部-Java开发工程师"
      }, {
        "taskId": 264,
        "status": 1,
        "taskType": 1,
        "dealUserName": "熊文鹏-产品研发部-Java开发工程师"
      }, {
        "taskId": 275,
        "status": 1,
        "taskType": 1,
        "dealUserName": "熊文鹏-产品研发部-Java开发工程师"
      }, {
        "taskId": 276,
        "status": 1,
        "taskType": 1,
        "dealUserName": "张慧洁-产品研发部-技术支持工程师"
      }, {
        "taskId": 281,
        "status": 1,
        "taskType": 1,
        "dealUserName": "小宇测试(业务员)-产品研发部-CEO"
      }, {
        "taskId": 287,
        "status": 1,
        "taskType": 1,
        "dealUserName": "李亮雪-产品研发部-产品经理"
      }, {
        "taskId": 362,
        "status": 1,
        "taskType": 2,
        "dealUserName": "周云萍-测试分公司-运维主管"
      }],
      "updateTime": "2020-09-10 16:28:38",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 234217,
      "terminal": "0000001370634307",
      "deviceType": "NAS-08",
      "shop": {
        "name": "大大",
        "address": "广东省深圳市福田区华强北街道振兴路341号女人世界外贸城(振兴路)大大"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.547238,
        "lng": 114.08592
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 0,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:344"],
      "updateTime": "2020-08-12 14:18:42",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }, {
      "deviceId": 232165,
      "terminal": "0000000158196542",
      "deviceType": "NAS-08",
      "shop": {
        "name": "嘿嘿嘿",
        "address": "广东省深圳市福田区华强北街道振兴路343号女人世界外贸城(振兴路)发射点发射点发"
      },
      "healthScore": 0,
      "coord": {
        "lat": 22.547216,
        "lng": 114.085951
      },
      "deviceState": 3,
      "offlineTime": "344天20小时",
      "totalChannel": 0,
      "currCDBCnt": 0,
      "rentNotReturnCnt": 0,
      "avgRentTimes": 0,
      "exceptionItem": ["离线超时天数:344"],
      "updateTime": "2020-08-12 14:18:42",
      "takeOfferCnt": 0,
      "reasonableValue": 0
    }],
    "total": 441,
    "size": 20,
    "current": 1,
    "searchCount": true,
    "pages": 23
  }